# podman-compose.override.yml (User creates this file)
version: '0.1'

services:
  orchestrator:
    environment:
      OPENAI_API_KEY: ""
##      OPENAI_model: ""
##      OLLAMA_BASE_URL: ""
##      OLLAMA_MODEL: ""
##      SYSTEM_ROLE_PROMPT_PERSONA: "You are an expert systems engineer."
#      # Finance and Trading Services
#      ALEUTIAN_TIMESERIES_TOOL: http://finance-analysis-service:8000
#      ALEUTIAN_DATA_FETCHER_URL: http://finance-data-service:8000
#      SAPHENEIA_TRADING_SERVICE_URL: http://sapheneia-trading-service:9000
#      SAPHENEIA_TRADING_API_KEY: default_trading_api_key_please_change
#      WEAVIATE_SERVICE_URL: ""
#      # InfluxDB Configuration (for trading signal handler)
#      INFLUXDB_URL: http://influxdb:8086
#      INFLUXDB_TOKEN: your_super_secret_admin_token
#      INFLUXDB_ORG: aleutian-finance
#      INFLUXDB_BUCKET: financial-data
#    depends_on:
#      finance-analysis-service:
#        condition: service_healthy
#      finance-data-service:
#        condition: service_healthy
#      sapheneia-trading-service:
#        condition: service_healthy
#  # Override the LLM command if you've downloaded a different model
#  # llm-server:
#  #   command: -m /models/my-other-model.gguf -c 8192 --n_gpu_layers -1
#
#  # Add the InfluxDB instance
#  influxdb:
#    image: influxdb:latest
#    container_name: user-influxdb
#    ports:
#      - "12130:8086"
#    volumes:
#      - influxdb_data:/var/lib/influxdb2
#    networks:
#      - aleutian-network
#    environment:
#      - DOCKER_INFLUXDB_INIT_MODE=setup
#      - DOCKER_INFLUXDB_INIT_USERNAME=admin
#      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
#      - DOCKER_INFLUXDB_INIT_ORG=aleutian-finance
#      - DOCKER_INFLUXDB_INIT_BUCKET=financial-data
#      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your_super_secret_admin_token
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8086/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 20
#
#  finance-data-service:
#    build:
#      context: /Users/jin/GolandProjects/SapheneiaAleutianMLOps/services/finance-data
#      dockerfile: Dockerfile
#    container_name: sapheneia-finance-data
#    ports:
#      - "12131:8000"
#    networks:
#      - aleutian-network
#    environment:
#      INFLUXDB_URL: http://influxdb:8086
#      INFLUXDB_TOKEN: your_super_secret_admin_token
#      INFLUXDB_ORG: aleutian-finance
#      INFLUXDB_BUCKET: financial-data
#    depends_on:
#      influxdb:
#        condition: service_healthy
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 20
#
#
#  finance-analysis-service:
#    build:
#      context: /Users/jin/GolandProjects/SapheneiaAleutianMLOps/services/finance-analysis
#      dockerfile: Dockerfile
#    container_name: sapheneia-timeseries-analysis
#    ports:
#      - "12129:8000"
#    networks:
#      - aleutian-network
#    environment:
#      - INFLUXDB_URL=http://influxdb:8086
#      - INFLUXDB_TOKEN=your_super_secret_admin_token
#      - INFLUXDB_ORG=aleutian-finance
#      - INFLUXDB_BUCKET=financial-data
#    volumes:
#      - models_cache:/root/.cache/huggingface/
#    secrets:
#      - source: aleutian_hf_token
#    depends_on:
#      influxdb:
#        condition: service_healthy
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 20
#
#  sapheneia-trading-service:
#    build:
#      context: /Users/jin/PycharmProjects/sapheneia
#      dockerfile: Dockerfile.trading
#    container_name: sapheneia-trading-service
#    ports:
#      - "12132:9000"
#    networks:
#      - aleutian-network
#    environment:
#      - TRADING_API_KEY=default_trading_api_key_please_change
#      - TRADING_API_PORT=9000
#      - TRADING_API_HOST=0.0.0.0
#      - ENVIRONMENT=production
#      - LOG_LEVEL=INFO
#      - RATE_LIMIT_ENABLED=true
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9000/health" ]
#      interval: 10s
#      timeout: 5s
#      retries: 20
#
#  aleutian-rag-engine:
#    environment:
#      RAG_PROMPT_TEMPLATE: "Context: {context}\n\nBased ONLY on the context, answer: {query}\nAnswer:"
#
#
#volumes:
#  influxdb_data: {}
