# podman-compose.test.yml
secrets:
  aleutian_hf_token:
    external: true

services:
  gguf-converter:
    build:
      context: .
      dockerfile: ./services/gguf_converter/Dockerfile
      args:
        - VERSION=${VERSION:-$(cat VERSION.txt)}
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-}
    container_name: aleutian-gguf-converter-test
    ports:
      - "12140:8000"
    volumes:
      - ./models:/models
      - ./models_cache:/root/.cache/huggingface/
    secrets:
      - source: aleutian_hf_token

volumes:
  models_cache: {}