# Aleutian Forecast Service
# This file is conditionally loaded when forecast.mode = "standalone"
# It provides the time-series forecasting capability as part of Aleutian

version: '3.8'

services:
  forecast-service:
    build:
      context: ./services/forecast
      dockerfile: Dockerfile
    container_name: aleutian-forecast
    ports: ["12000:8000"]
    environment:
      PORT: 8000
      DEFAULT_MODEL: ""
      # Use appuser's home directory (container runs as appuser, not root)
      HF_HOME: /home/appuser/.cache/huggingface
      TRANSFORMERS_CACHE: /home/appuser/.cache/huggingface/transformers
    volumes:
      - ${ALEUTIAN_MODELS_CACHE:-./models_cache}:/home/appuser/.cache/huggingface
    networks:
      - aleutian-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 120s
      retries: 3

networks:
  aleutian-network:
    external: true
    name: ${ALEUTIAN_NETWORK_NAME:-aleutian-shared}
