# Aleutian Standalone Configuration
# This compose file runs Aleutian WITHOUT Sapheneia dependency.
# All services are self-contained within Aleutian.
#
# Usage:
#   podman-compose -f podman-compose.standalone.yml up -d
#
# For GPU support on Ubuntu RTX 5090:
#   FORECAST_GPU=true podman-compose -f podman-compose.standalone.yml up -d

version: '3.8'

secrets:
  aleutian_hf_token:
    external: true

services:
  # === 1. Forecast Service (Standalone - replaces Sapheneia) ===
  forecast-service:
    build:
      context: ./services/forecast
      dockerfile: ${FORECAST_GPU:-false} == "true" && Dockerfile.gpu || Dockerfile
    container_name: aleutian-forecast
    ports: ["12000:8000"]
    environment:
      PORT: 8000
      DEFAULT_MODEL: chronos-t5-tiny
      # HuggingFace cache for model downloads (container runs as appuser, not root)
      HF_HOME: /home/appuser/.cache/huggingface
      TRANSFORMERS_CACHE: /home/appuser/.cache/huggingface/transformers
    volumes:
      - ${ALEUTIAN_MODELS_CACHE:-./models_cache}:/home/appuser/.cache/huggingface
    networks:
      - aleutian-standalone
    restart: unless-stopped
    # Uncomment for GPU support:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      start_period: 120s
      retries: 3

  # === 2. The Orchestrator ===
  orchestrator:
    build:
      context: .
      dockerfile: ./services/orchestrator/Dockerfile
    container_name: aleutian-go-orchestrator
    ports: ["12210:12210"]
    environment:
      PORT: 12210
      # Standalone mode - all forecasts go to unified service
      ALEUTIAN_TIMESERIES_TOOL: http://forecast-service:8000
      ALEUTIAN_FORECAST_MODE: standalone
      # Data fetcher - TODO: implement standalone version
      ALEUTIAN_DATA_FETCHER_URL: ""
      # Trading service - uses internal handlers
      SAPHENEIA_TRADING_SERVICE_URL: ""
      # InfluxDB Config
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_TOKEN: your_super_secret_admin_token
      INFLUXDB_ORG: aleutian-finance
      INFLUXDB_BUCKET: financial-data
      # Observability
      OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
    volumes:
      - ./internal/policy_engine/enforcement/data_classification_patterns.yaml:/app/internal/policy_engine/enforcement/data_classification_patterns.yaml:ro
    networks:
      - aleutian-standalone
    restart: unless-stopped
    depends_on:
      forecast-service:
        condition: service_healthy
      otel-collector:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12210/health"]
      interval: 10s
      timeout: 5s
      retries: 20

  # === 3. InfluxDB ===
  influxdb:
    image: influxdb:2.7
    container_name: aleutian-influxdb
    ports: ["12130:8086"]
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - aleutian-standalone
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=aleutian-finance
      - DOCKER_INFLUXDB_INIT_BUCKET=financial-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your_super_secret_admin_token
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 20

  # === 4. Observability Stack ===
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: aleutian-otel-collector
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    volumes:
      - ./observability/otel_collector_config.yaml:/etc/otelcol-contrib/config.yaml:ro
    ports: ["4317:4317", "4318:4318", "8889:8889"]
    networks:
      - aleutian-standalone
    depends_on:
      - aleutian-jaeger

  aleutian-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: aleutian-jaeger
    ports: ["16686:16686"]
    networks:
      - aleutian-standalone
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686/"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: aleutian-prometheus
    volumes:
      - ./observability/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    ports: ["9090:9090"]
    networks:
      - aleutian-standalone
    depends_on:
      - otel-collector
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: aleutian-grafana
    ports: ["3000:3000"]
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    networks:
      - aleutian-standalone
    depends_on:
      - prometheus
      - aleutian-jaeger
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  influxdb_data: {}
  models_cache: {}
  grafana_data: {}

networks:
  aleutian-standalone:
    driver: bridge
    name: aleutian-standalone
