apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://aleutian-prometheus:9090
    isDefault: true

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://aleutian-jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: 'prometheus'