---
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
  prometheus:
    config:
      scrape_configs:
        - job_name: "ollama"
          static_configs:
            - targets: ['host.containers.internal:11434']

processors:
  batch: # batches data before exporting

exporters:
  otlp: # exports traces to jaeger
    endpoint: "aleutian-jaeger:4317"
    tls:
      insecure: true
  prometheus: # exports metrics to prometheus
    endpoint: "0.0.0.0:8889"
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus, debug]