# Default configuration for AleutianLocal
target: local # Default target is local execution
server_host: "" # Not needed for local target

# Default service configurations (ports are essential defaults)
services:
  orchestrator:
    port: 12210
  embedding-server:
    port: 12126
  gguf-converter:
    port: 12140
  rag-engine:
    port: 12125
  weaviate-db:
    port: 12127
    grpc_port: 50051