# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "aleutian-client"
version = "0.1.0"
authors = [
    { name="John", email="jinterlante@aleutian.ai" },
]
description = "The official Python client SDK for the AleutianLocal MLOps platform."
readme = "README.md"
license = { file="LICENSE.txt" }
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
keywords = ["aleutian", "mlops", "local-ai", "rag", "sdk"]

dependencies = [
    "httpx>=0.25.0",
    "pydantic>=2.0",
]

[project.urls]
"Homepage" = "https://github.com/jinterlante1206/AleutianLocal"
"Bug Tracker" = "https://github.com/jinterlante1206/AleutianLocal/issues"